# Generated by Django 3.1.2 on 2021-05-26 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像4')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'あなたの夢',
                'verbose_name_plural': 'あなたの夢',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像4')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yumenikki.dreammodel', verbose_name='Dream')),
            ],
            options={
                'verbose_name': 'アイデア',
                'verbose_name_plural': 'アイデア',
            },
        ),
        migrations.AddField(
            model_name='dreammodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='yumenikki.Tag'),
        ),
    ]
