# Generated by Django 3.1.2 on 2021-03-01 07:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(upload_to='', verbose_name='画像を投稿')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日')),
            ],
            options={
                'verbose_name': 'あなたの夢',
                'verbose_name_plural': 'あなたの夢',
            },
        ),
        migrations.CreateModel(
            name='IdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(upload_to='', verbose_name='画像を投稿')),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yumenikki.dreammodel', verbose_name='Dream')),
            ],
            options={
                'verbose_name': 'あなたの夢',
                'verbose_name_plural': 'あなたの夢',
            },
        ),
        migrations.DeleteModel(
            name='TodoModel',
        ),
    ]
