# Generated by Django 3.1.2 on 2021-03-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0002_auto_20210301_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideamodel',
            options={'verbose_name': 'アイデア', 'verbose_name_plural': 'アイデア'},
        ),
    ]
