# Generated by Django 3.1.2 on 2021-05-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
