# Generated by Django 3.1.2 on 2021-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0003_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='DreamTag',
        ),
        migrations.RemoveField(
            model_name='dreammodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='dreammodel',
            name='dtags',
            field=models.ManyToManyField(blank=True, to='yumenikki.DreamTag'),
        ),
    ]
