# Generated by Django 3.1.2 on 2021-03-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0004_auto_20210301_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreammodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='画像を投稿'),
        ),
    ]
