# Generated by Django 3.1.2 on 2021-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0005_auto_20210301_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideamodel',
            name='image',
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像1'),
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像2'),
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像3'),
        ),
        migrations.AddField(
            model_name='ideamodel',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='画像4'),
        ),
    ]
