# Generated by Django 3.1.2 on 2021-05-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0009_auto_20210521_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
