# Generated by Django 3.1.2 on 2021-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumenikki', '0010_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreammodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
